/**
 * Minimal, dependency-free QR Code encoder -- byte mode (ISO/IEC 18004).
 *
 * Why hand-written (T-194): the pairing screen renders the QR that the desktop
 * displays (`docs/contracts/authenticator.md` §3.1). React Native has no
 * built-in QR renderer and the scaffold ships a deliberately tiny dependency
 * set (no native modules, no runtime deps), so the matrix is produced here and
 * drawn as plain Views.
 *
 * Correctness evidence: `tests/qr/qrcode.test.ts` compares this encoder's
 * matrices module-for-module against reference matrices generated by segno
 * (an independent implementation) -- see `tests/fixtures/qr-vectors.ts` and
 * `tools/gen-qr-vectors.py`. Supported: byte mode, EC levels L/M, versions
 * 1..25 (larger payloads are rejected rather than silently mis-encoded).
 *
 * Scope: this encoder renders a *payload*. It does not validate, parse, or
 * trust the payload -- `protocol/qr.ts` owns that (SECURITY.md rule 9).
 */
/* eslint-disable no-bitwise -- QR symbol construction is bit-level by nature. */
import { EC_BLOCKS, MAX_QR_VERSION, type EcBlockGroup, type EcLevel } from './tables';

export type { EcLevel };

export interface QrMatrix {
  readonly version: number;
  readonly ecLevel: EcLevel;
  readonly mask: number;
  /** Modules per side: 17 + 4 * version. */
  readonly size: number;
  /** `modules[row][col] === true` means a dark module. Quiet zone excluded. */
  readonly modules: readonly (readonly boolean[])[];
}

export class QrEncodeError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'QrEncodeError';
  }
}

/** Recommended quiet zone in modules (ISO/IEC 18004 §6.3.2.3). */
export const QR_QUIET_ZONE = 4;

// ---------------------------------------------------------------------------
// GF(256) arithmetic, primitive polynomial 0x11D (ISO/IEC 18004 §7.5).
// ---------------------------------------------------------------------------

const GF_EXP = new Uint8Array(512);
const GF_LOG = new Uint8Array(256);

function initGaloisField(): void {
  let x = 1;
  for (let i = 0; i < 255; i++) {
    GF_EXP[i] = x;
    GF_LOG[x] = i;
    x <<= 1;
    if ((x & 0x100) !== 0) {x ^= 0x11d;}
  }
  for (let i = 255; i < 512; i++) {GF_EXP[i] = GF_EXP[i - 255] ?? 0;}
}
initGaloisField();

function gfMul(a: number, b: number): number {
  if (a === 0 || b === 0) {return 0;}
  return GF_EXP[(GF_LOG[a] ?? 0) + (GF_LOG[b] ?? 0)] ?? 0;
}

/**
 * Reed-Solomon divisor for `degree` EC codewords: the coefficients of
 * `prod (x - a^i)` for i in 0..degree-1, excluding the leading 1, highest
 * power first.
 */
function rsDivisor(degree: number): Uint8Array {
  const result = new Uint8Array(degree);
  result[degree - 1] = 1;
  let root = 1;
  for (let i = 0; i < degree; i++) {
    for (let j = 0; j < degree; j++) {
      result[j] = gfMul(result[j] ?? 0, root);
      if (j + 1 < degree) {result[j] = (result[j] ?? 0) ^ (result[j + 1] ?? 0);}
    }
    root = gfMul(root, 0x02);
  }
  return result;
}

/** Remainder of `data * x^divisor.length` divided by the RS divisor. */
function rsRemainder(data: ArrayLike<number>, divisor: Uint8Array): Uint8Array {
  const result = new Uint8Array(divisor.length);
  for (let k = 0; k < data.length; k++) {
    const factor = (data[k] ?? 0) ^ (result[0] ?? 0);
    result.copyWithin(0, 1);
    result[result.length - 1] = 0;
    for (let i = 0; i < result.length; i++) {
      result[i] = (result[i] ?? 0) ^ gfMul(divisor[i] ?? 0, factor);
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Data encoding: byte mode (ISO/IEC 18004 §7.4.3).
// ---------------------------------------------------------------------------

const MODE_BYTE = 0b0100;
const PAD_BYTES = [0xec, 0x11];

/** UTF-8 bytes without TextEncoder (React Native has no guaranteed global). */
export function toUtf8Bytes(text: string): Uint8Array {
  const out: number[] = [];
  for (let i = 0; i < text.length; i++) {
    let cp = text.charCodeAt(i);
    // Combine surrogate pairs (U+10000..U+10FFFF) into one code point.
    if (cp >= 0xd800 && cp <= 0xdbff && i + 1 < text.length) {
      const low = text.charCodeAt(i + 1);
      if (low >= 0xdc00 && low <= 0xdfff) {
        cp = 0x10000 + ((cp - 0xd800) << 10) + (low - 0xdc00);
        i += 1;
      }
    }
    if (cp < 0x80) {
      out.push(cp);
    } else if (cp < 0x800) {
      out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
    } else if (cp < 0x10000) {
      out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
    } else {
      out.push(
        0xf0 | (cp >> 18),
        0x80 | ((cp >> 12) & 0x3f),
        0x80 | ((cp >> 6) & 0x3f),
        0x80 | (cp & 0x3f),
      );
    }
  }
  return new Uint8Array(out);
}

/** Character-count indicator width for byte mode (ISO/IEC 18004 Table 3). */
function charCountBits(version: number): number {
  return version <= 9 ? 8 : 16;
}

function blocksFor(version: number, level: EcLevel): readonly EcBlockGroup[] {
  const perVersion = EC_BLOCKS[version];
  if (perVersion === undefined) {throw new QrEncodeError(`no EC table for version ${version}`);}
  return perVersion[level];
}

/** Total data codewords (all blocks) available at this version + level. */
export function dataCapacityCodewords(version: number, level: EcLevel): number {
  return blocksFor(version, level).reduce(
    (sum, g) => sum + g.count * g.dataCodewords,
    0,
  );
}

function requiredDataBits(version: number, byteLength: number): number {
  return 4 + charCountBits(version) + byteLength * 8;
}

/** Smallest version that fits `byteLength` bytes at `level` (throws if none). */
export function chooseVersion(byteLength: number, level: EcLevel): number {
  for (let version = 1; version <= MAX_QR_VERSION; version++) {
    if (requiredDataBits(version, byteLength) <= dataCapacityCodewords(version, level) * 8) {
      return version;
    }
  }
  throw new QrEncodeError(
    `payload of ${byteLength} bytes exceeds version ${MAX_QR_VERSION} capacity at level ${level}`,
  );
}

class BitBuffer {
  private readonly bits: number[] = [];

  put(value: number, length: number): void {
    for (let i = length - 1; i >= 0; i--) {this.bits.push((value >> i) & 1);}
  }

  get length(): number {
    return this.bits.length;
  }

  toBytes(): Uint8Array {
    const out = new Uint8Array(Math.ceil(this.bits.length / 8));
    for (let i = 0; i < this.bits.length; i++) {
      if (this.bits[i] === 1) {out[i >>> 3] = (out[i >>> 3] ?? 0) | (0x80 >> (i & 7));}
    }
    return out;
  }
}

/** Mode + count + payload + terminator + padding, as data codewords. */
function buildDataCodewords(bytes: Uint8Array, version: number, level: EcLevel): Uint8Array {
  const capacity = dataCapacityCodewords(version, level);
  const buf = new BitBuffer();
  buf.put(MODE_BYTE, 4);
  buf.put(bytes.length, charCountBits(version));
  for (let i = 0; i < bytes.length; i++) {buf.put(bytes[i] ?? 0, 8);}
  // Terminator (up to 4 zero bits, truncated if it would overrun capacity).
  const terminator = Math.min(4, capacity * 8 - buf.length);
  buf.put(0, terminator);
  // Pad to a byte boundary, then alternate pad codewords.
  buf.put(0, (8 - (buf.length % 8)) % 8);
  const out = buf.toBytes();
  const codewords = new Uint8Array(capacity);
  codewords.set(out);
  for (let i = out.length, k = 0; i < capacity; i++, k++) {
    codewords[i] = PAD_BYTES[k % PAD_BYTES.length] ?? 0;
  }
  return codewords;
}

/**
 * Split data codewords into blocks, append each block's EC codewords, and
 * interleave (ISO/IEC 18004 §7.6).
 */
function interleaveCodewords(data: Uint8Array, version: number, level: EcLevel): Uint8Array {
  const groups = blocksFor(version, level);
  const dataBlocks: Uint8Array[] = [];
  const ecBlocks: Uint8Array[] = [];
  let offset = 0;
  for (const group of groups) {
    for (let b = 0; b < group.count; b++) {
      const block = data.subarray(offset, offset + group.dataCodewords);
      offset += group.dataCodewords;
      dataBlocks.push(block);
      const ecLen = group.totalCodewords - group.dataCodewords;
      const divisor = rsDivisor(ecLen);
      ecBlocks.push(rsRemainder(block, divisor));
    }
  }
  const out: number[] = [];
  const maxData = Math.max(...dataBlocks.map((b) => b.length));
  for (let i = 0; i < maxData; i++) {
    for (const block of dataBlocks) {
      if (i < block.length) {out.push(block[i] ?? 0);}
    }
  }
  const maxEc = Math.max(...ecBlocks.map((b) => b.length));
  for (let i = 0; i < maxEc; i++) {
    for (const block of ecBlocks) {
      if (i < block.length) {out.push(block[i] ?? 0);}
    }
  }
  return new Uint8Array(out);
}


// ---------------------------------------------------------------------------
// Symbol construction: function patterns, data placement, masking (§6, §7).
// ---------------------------------------------------------------------------

/** Remainder bits appended after all codewords, by version (ISO/IEC 18004 Table 1). */
function remainderBits(version: number): number {
  if (version === 1) {return 0;}
  if (version <= 6) {return 7;}
  if (version <= 13) {return 0;}
  if (version <= 20) {return 3;}
  return 4; // versions 21..25 (this encoder's range)
}

/** Alignment-pattern centre coordinates (ISO/IEC 18004 Annex E). */
export function alignmentCenters(version: number): number[] {
  if (version === 1) {return [];}
  const size = version * 4 + 17;
  const numAlign = Math.floor(version / 7) + 2;
  const step = version === 32 ? 26 : Math.ceil((version * 4 + 4) / (numAlign * 2 - 2)) * 2;
  const result: number[] = [6];
  for (let pos = size - 7; result.length < numAlign; pos -= step) {result.splice(1, 0, pos);}
  return result;
}

interface Canvas {
  readonly size: number;
  readonly isFunction: boolean[][];
  readonly modules: boolean[][];
}

function emptyCanvas(size: number): Canvas {
  const isFunction = Array.from({ length: size }, () => Array.from({ length: size }, () => false));
  const modules = Array.from({ length: size }, () => Array.from({ length: size }, () => false));
  return { size, isFunction, modules };
}

function setFunction(c: Canvas, row: number, col: number, dark: boolean): void {
  c.modules[row]![col] = dark;
  c.isFunction[row]![col] = true;
}

function drawFinder(c: Canvas, centerRow: number, centerCol: number): void {
  const size = c.size;
  for (let dr = -4; dr <= 4; dr++) {
    for (let dc = -4; dc <= 4; dc++) {
      const row = centerRow + dr;
      const col = centerCol + dc;
      if (row < 0 || row >= size || col < 0 || col >= size) {continue;}
      const dist = Math.max(Math.abs(dr), Math.abs(dc));
      setFunction(c, row, col, dist !== 2 && dist !== 4);
    }
  }
}

function drawFunctionPatterns(c: Canvas, version: number): void {
  const size = c.size;
  // Timing patterns (row 6 / col 6, dark at even coordinates).
  for (let i = 0; i < size; i++) {
    setFunction(c, 6, i, i % 2 === 0);
    setFunction(c, i, 6, i % 2 === 0);
  }
  // Finder patterns + separators, drawn over the timing rows at the corners.
  drawFinder(c, 3, 3);
  drawFinder(c, 3, size - 4);
  drawFinder(c, size - 4, 3);
  // Alignment patterns (skipping the three that overlap finder patterns).
  const centers = alignmentCenters(version);
  const last = centers.length - 1;
  for (let i = 0; i < centers.length; i++) {
    for (let j = 0; j < centers.length; j++) {
      if ((i === 0 && j === 0) || (i === 0 && j === last) || (i === last && j === 0)) {continue;}
      const row = centers[i] ?? 0;
      const col = centers[j] ?? 0;
      for (let dr = -2; dr <= 2; dr++) {
        for (let dc = -2; dc <= 2; dc++) {
          setFunction(c, row + dr, col + dc, Math.max(Math.abs(dr), Math.abs(dc)) !== 1);
        }
      }
    }
  }
  // Reserve the format-information areas (values written after masking) and
  // the always-dark module at (size-8, 8).
  drawFormatBits(c, 0, /* reserveOnly */ true);
  // Reserve version-information areas for versions >= 7.
  if (version >= 7) {
    for (let i = 0; i < 18; i++) {
      const a = size - 11 + (i % 3);
      const b = Math.floor(i / 3);
      setFunction(c, b, a, false);
      setFunction(c, a, b, false);
    }
  }
  setFunction(c, size - 8, 8, true);
}

/** Place the interleaved codewords in the zigzag pattern (ISO/IEC 18004 §7.7.3). */
function drawCodewords(c: Canvas, codewords: Uint8Array): void {
  const size = c.size;
  const totalBits = codewords.length * 8;
  let i = 0;
  for (let right = size - 1; right >= 1; right -= 2) {
    if (right === 6) {right = 5;} // skip the vertical timing column
    for (let vert = 0; vert < size; vert++) {
      for (let j = 0; j < 2; j++) {
        const col = right - j;
        const upward = ((right + 1) & 2) === 0;
        const row = upward ? size - 1 - vert : vert;
        if (!c.isFunction[row]![col] && i < totalBits) {
          c.modules[row]![col] =
            (((codewords[i >>> 3] ?? 0) >>> (7 - (i & 7))) & 1) !== 0;
          i++;
        }
      }
    }
  }
  if (i !== totalBits) {throw new QrEncodeError('internal: codeword placement overflow');}
  // Remainder bits keep their light default.
}

/** Mask condition per pattern index (ISO/IEC 18004 Table 10, i = row, j = col). */
export function maskApplies(mask: number, row: number, col: number): boolean {
  switch (mask) {
    case 0: return (row + col) % 2 === 0;
    case 1: return row % 2 === 0;
    case 2: return col % 3 === 0;
    case 3: return (row + col) % 3 === 0;
    case 4: return (Math.floor(row / 2) + Math.floor(col / 3)) % 2 === 0;
    case 5: return ((row * col) % 2) + ((row * col) % 3) === 0;
    case 6: return (((row * col) % 2) + ((row * col) % 3)) % 2 === 0;
    case 7: return (((row + col) % 2) + ((row * col) % 3)) % 2 === 0;
    default: throw new QrEncodeError(`unknown mask pattern ${mask}`);
  }
}

/** Apply one mask to the data region of a copy of the canvas. */
function withMask(c: Canvas, mask: number): Canvas {
  const copy = emptyCanvas(c.size);
  for (let row = 0; row < c.size; row++) {
    for (let col = 0; col < c.size; col++) {
      copy.isFunction[row]![col] = c.isFunction[row]![col]!;
      const dark = c.modules[row]![col]!;
      copy.modules[row]![col] = !c.isFunction[row]![col] && maskApplies(mask, row, col) ? !dark : dark;
    }
  }
  return copy;
}


// --- mask penalty (ISO/IEC 18004 §7.8.3, same reading as the reference impl) ---

const N3_PATTERN = [1, 0, 1, 1, 1, 0, 1];

function indexOfPattern(seq: Uint8Array, from: number): number {
  for (let i = Math.max(from, 0); i + N3_PATTERN.length <= seq.length; i++) {
    let match = true;
    for (let k = 0; k < N3_PATTERN.length; k++) {
      if ((seq[i + k] ?? 0) !== N3_PATTERN[k]) {match = false; break;}
    }
    if (match) {return i;}
  }
  return -1;
}

function noDarkModules(seq: Uint8Array, from: number, to: number): boolean {
  const start = Math.max(from, 0);
  const end = Math.min(to, seq.length);
  for (let i = start; i < end; i++) {
    if ((seq[i] ?? 0) !== 0) {return false;}
  }
  return true;
}

function n3Score(seq: Uint8Array, size: number): number {
  let score = 0;
  let idx = indexOfPattern(seq, 0);
  while (idx !== -1) {
    let offset = idx + N3_PATTERN.length;
    const atEdge = idx === 0 || idx === size - N3_PATTERN.length;
    if (atEdge || noDarkModules(seq, idx - 4, idx) || noDarkModules(seq, offset, offset + 4)) {
      score += 40;
    } else {
      // Not enough light modules on either side: resume search one dark short
      // so overlapping candidates are still considered.
      offset = idx + 4;
    }
    idx = indexOfPattern(seq, offset);
  }
  return score;
}

/** Penalty score used to pick the mask; lower is better. */
export function maskPenalty(c: Canvas): number {
  const size = c.size;
  let n1 = 0;
  let n2 = 0;
  let n3 = 0;
  let dark = 0;
  const column = new Uint8Array(size);
  for (let row = 0; row < size; row++) {
    let rowRunValue = -1;
    let rowRun = 0;
    let colRunValue = -1;
    let colRun = 0;
    for (let col = 0; col < size; col++) {
      const bit = c.modules[row]![col]! ? 1 : 0;
      column[col] = c.modules[col]![row]! ? 1 : 0;
      if (bit === 1) {dark++;}
      // N1 -- rows
      if (bit === rowRunValue) {
        rowRun++;
      } else {
        if (rowRun >= 5) {n1 += rowRun - 2;}
        rowRunValue = bit;
        rowRun = 1;
      }
      // N1 -- columns
      const colBit = column[col] ?? 0;
      if (colBit === colRunValue) {
        colRun++;
      } else {
        if (colRun >= 5) {n1 += colRun - 2;}
        colRunValue = colBit;
        colRun = 1;
      }
      // N2 -- 2x2 blocks of one colour
      if (row > 0 && col > 0) {
        const up = c.modules[row - 1]![col]! ? 1 : 0;
        const left = c.modules[row]![col - 1]! ? 1 : 0;
        const diag = c.modules[row - 1]![col - 1]! ? 1 : 0;
        if (bit === up && bit === left && bit === diag) {n2 += 3;}
      }
    }
    if (rowRun >= 5) {n1 += rowRun - 2;}
    if (colRun >= 5) {n1 += colRun - 2;}
    const rowBits = new Uint8Array(size);
    for (let col = 0; col < size; col++) {rowBits[col] = c.modules[row]![col]! ? 1 : 0;}
    n3 += n3Score(rowBits, size);
    n3 += n3Score(column, size);
  }
  // N4 -- deviation of the dark proportion from 50%.
  const percent = dark / (size * size);
  const n4 = 10 * Math.floor(Math.abs(percent * 100 - 50) / 5);
  return n1 + n2 + n3 + n4;
}

// --- format / version information (§7.9, §7.10) ---

/** 15-bit format information: EC level + mask, BCH(15,5) + XOR mask. */
export function formatBits(level: EcLevel, mask: number): number {
  const levelBits = level === 'L' ? 0b01 : 0b00;
  const data = (levelBits << 3) | mask;
  let value = data << 10;
  for (let i = 4; i >= 0; i--) {
    if ((value & (1 << (i + 10))) !== 0) {value ^= 0x537 << i;}
  }
  return ((data << 10) | value) ^ 0x5412;
}

/** 18-bit version information (versions >= 7): BCH(18,6). */
export function versionBits(version: number): number {
  let value = version << 12;
  for (let i = 5; i >= 0; i--) {
    if ((value & (1 << (i + 12))) !== 0) {value ^= 0x1f25 << i;}
  }
  return (version << 12) | value;
}

function drawFormatBits(c: Canvas, mask: number, reserveOnly = false, level: EcLevel = 'L'): void {
  if (reserveOnly) {
    for (let i = 0; i <= 5; i++) {setFunction(c, i, 8, false);}
    setFunction(c, 7, 8, false);
    setFunction(c, 8, 8, false);
    setFunction(c, 8, 7, false);
    for (let i = 9; i < 15; i++) {setFunction(c, 8, 14 - i, false);}
    for (let i = 0; i < 8; i++) {setFunction(c, 8, c.size - 1 - i, false);}
    for (let i = 8; i < 15; i++) {setFunction(c, c.size - 15 + i, 8, false);}
    return;
  }
  const bits = formatBits(level, mask);
  const bit = (i: number): boolean => ((bits >>> i) & 1) !== 0;
  for (let i = 0; i <= 5; i++) {setFunction(c, i, 8, bit(i));}
  setFunction(c, 7, 8, bit(6));
  setFunction(c, 8, 8, bit(7));
  setFunction(c, 8, 7, bit(8));
  for (let i = 9; i < 15; i++) {setFunction(c, 8, 14 - i, bit(i));}
  for (let i = 0; i < 8; i++) {setFunction(c, 8, c.size - 1 - i, bit(i));}
  for (let i = 8; i < 15; i++) {setFunction(c, c.size - 15 + i, 8, bit(i));}
  setFunction(c, c.size - 8, 8, true); // always dark
}

function drawVersionBits(c: Canvas, version: number): void {
  if (version < 7) {return;}
  const bits = versionBits(version);
  const size = c.size;
  for (let i = 0; i < 18; i++) {
    const dark = ((bits >>> i) & 1) !== 0;
    const a = size - 11 + (i % 3);
    const b = Math.floor(i / 3);
    setFunction(c, b, a, dark);
    setFunction(c, a, b, dark);
  }
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

export interface EncodeOptions {
  readonly ecLevel?: EcLevel;
  /**
   * Force a mask pattern (0..7) instead of running the §7.8.3 evaluation.
   * Tests and diagnostics use this to compare one stage at a time; the
   * pairing screen never sets it.
   */
  readonly mask?: number;
}

/**
 * Encode `text` (UTF-8, byte mode) into a QR module matrix.
 *
 * The mask is chosen by evaluating all eight patterns and keeping the lowest
 * penalty (ISO/IEC 18004 §7.8.3, ties resolved by lowest mask index). Format
 * and version information are added *after* mask selection, as the standard
 * specifies -- evaluating them first changes the chosen mask and silently
 * breaks scanner interoperability.
 */
export function encodeQrMatrix(text: string, opts: EncodeOptions = {}): QrMatrix {
  const ecLevel = opts.ecLevel ?? 'M';
  if (typeof text !== 'string' || text.length === 0) {
    throw new QrEncodeError('qr payload must be a non-empty string');
  }
  const bytes = toUtf8Bytes(text);
  const version = chooseVersion(bytes.length, ecLevel);
  const size = version * 4 + 17;
  const data = buildDataCodewords(bytes, version, ecLevel);
  const codewords = interleaveCodewords(data, version, ecLevel);
  const canvas = emptyCanvas(size);
  drawFunctionPatterns(canvas, version);
  drawCodewords(canvas, codewords);

  let bestMask = opts.mask ?? 0;
  if (opts.mask === undefined) {
    let bestPenalty = Number.POSITIVE_INFINITY;
    for (let mask = 0; mask < 8; mask++) {
      const penalty = maskPenalty(withMask(canvas, mask));
      if (penalty < bestPenalty) {
        bestPenalty = penalty;
        bestMask = mask;
      }
    }
  } else if (opts.mask < 0 || opts.mask > 7) {
    throw new QrEncodeError(`mask must be 0..7, got ${opts.mask}`);
  }
  const masked = withMask(canvas, bestMask);
  drawFormatBits(masked, bestMask, false, ecLevel);
  drawVersionBits(masked, version);

  const modules = masked.modules.map((row) => Object.freeze(row.slice()));
  return {
    version,
    ecLevel,
    mask: bestMask,
    size,
    modules: Object.freeze(modules),
  };
}

/** Remainder-bit count for a version (0/3/4/7) -- exposed for diagnostics. */
export function qrRemainderBits(version: number): number {
  return remainderBits(version);
}


